const VARIANT_MAP = {
  default:       'badge-slate',
  primary:       'badge-indigo',
  accent:        'badge-green',
  danger:        'badge-red',
  warning:       'badge-amber',
  purple:        'badge-purple',
  blue:          'badge-blue',
  orange:        'badge-amber',
  muted:         'badge-slate',
  lost:          'badge-red',
  found:         'badge-green',
  available:     'badge-green',
  sold:          'badge-slate',
  reserved:      'badge-amber',
  pending:       'badge-amber',
  'in-progress': 'badge-indigo',
  completed:     'badge-green',
  internship:    'badge-blue',
  scholarship:   'badge-green',
  hackathon:     'badge-purple',
  job:           'badge-amber',
  competition:   'badge-amber',
  low:           'badge-green',
  medium:        'badge-amber',
  high:          'badge-red',
  new:           'badge-green',
  good:          'badge-blue',
  fair:          'badge-amber',
  poor:          'badge-red',
  announcement:  'badge-red',
  event:         'badge-indigo',
  recruitment:   'badge-green',
  general:       'badge-slate',
  hostel:        'badge-indigo',
  mess:          'badge-green',
  pg:            'badge-amber',
  hardware:      'badge-amber',
  stationery:    'badge-blue',
  other:         'badge-slate',
  technical:     'badge-indigo',
  cultural:      'badge-purple',
  sports:        'badge-green',
  social:        'badge-amber',
  income:        'badge-green',
  expense:       'badge-red',
};

export default function Badge({ children, variant = 'default', size }) {
  return (
    <span className={`badge ${VARIANT_MAP[variant] || 'badge-slate'}`}>
      {children}
    </span>
  );
}
